-- 014_seed_metrics.sql
-- Seed all base metrics from spec. ON CONFLICT DO NOTHING — не перезаписывает ручные правки.

INSERT INTO metrics (
  id, name_ru, name_short_ru, description,
  metric_type, data_type, formula, dependencies,
  decimal_places, aggregation_fn, category, sort_order,
  is_core, is_active, is_hidden_in_ui, is_test,
  source, agg_fn, agg_field, date_field, filters, tags,
  is_collect_ok, is_calc_ok, calc_ok, fill_ok
) VALUES

-- ══════════════════════════════════════════════
-- 2. АКТИВНОСТЬ
-- ══════════════════════════════════════════════

-- Изменено сделок: уникальные сделки с хотя бы одним событием за период
-- deal_events source с GROUP BY работает как correlated subquery — is_test до проверки
('changed_deals_count',
 'Изменено сделок', 'Изм. сделки',
 'Количество уникальных сделок, по которым было хотя бы одно событие (смена стадии) за период',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'activity', 100,
 false, false, false, true,
 'deal_events', 'count_distinct', 'deal_id', 'event_at', '[]'::jsonb,
 ARRAY['activity'],
 false, false, false, false),

-- ══════════════════════════════════════════════
-- 3. ОТКАЗЫ
-- ══════════════════════════════════════════════

('lost_deals_count',
 'Кол-во отказов', 'Отказы',
 'Количество сделок, перешедших в статус отказа за период (по дате отказа lost_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'refusals', 200,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'lost_at', '[]'::jsonb,
 ARRAY['refusals'],
 false, false, false, false),

-- ══════════════════════════════════════════════
-- 4. ПРОДАЖИ
-- ══════════════════════════════════════════════

('primary_deals_count',
 'Первичные сделки', 'Перв. сделки',
 'Количество первичных входящих сделок, созданных за период (воронки с is_repeat=false)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'sales', 300,
 true, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'created_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['sales','primary','incoming'],
 false, false, false, false),

('primary_sales_count',
 'Кол-во продаж (перв.)', 'Прод. перв.',
 'Количество первичных продаж за период (по дате продажи sold_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'sales', 310,
 true, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'sold_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['sales','primary'],
 false, false, false, false),

('repeat_sales_count',
 'Кол-во продаж (повт.)', 'Прод. повт.',
 'Количество повторных продаж за период (по дате продажи sold_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'sales', 320,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'sold_at',
 '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb,
 ARRAY['sales','repeat'],
 false, false, false, false),

('primary_sales_amount',
 'Сумма продаж (перв.)', 'Сумма перв.',
 'Сумма первичных продаж за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'sales', 330,
 true, false, false, false,
 'deals', 'sum', 'amount', 'sold_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['sales','primary','amount'],
 false, false, false, false),

('repeat_sales_amount',
 'Сумма продаж (повт.)', 'Сумма повт.',
 'Сумма повторных продаж за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'sales', 340,
 false, false, false, false,
 'deals', 'sum', 'amount', 'sold_at',
 '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb,
 ARRAY['sales','repeat','amount'],
 false, false, false, false),

('primary_sales_avg_amount',
 'Ср. чек продаж (перв.)', 'Ср. чек перв.',
 'Средний чек первичных продаж за период',
 'collected', 'money', NULL, '{}',
 0, 'avg', 'sales', 350,
 false, false, false, false,
 'deals', 'avg', 'amount', 'sold_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['sales','primary','avg'],
 false, false, false, false),

('all_sales_avg_amount',
 'Ср. чек продаж (все)', 'Ср. чек все',
 'Средний чек по всем продажам (первичные + повторные) за период',
 'collected', 'money', NULL, '{}',
 0, 'avg', 'sales', 360,
 false, false, false, false,
 'deals', 'avg', 'amount', 'sold_at', '[]'::jsonb,
 ARRAY['sales','avg'],
 false, false, false, false),

('primary_deals_avg_amount',
 'Ср. чек перв. сделок', 'Ср. чек сделок',
 'Средний чек первичных входящих сделок за период (по created_at)',
 'collected', 'money', NULL, '{}',
 0, 'avg', 'sales', 370,
 false, false, false, false,
 'deals', 'avg', 'amount', 'created_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['sales','primary','avg'],
 false, false, false, false),

-- % кол-во продаж повторных
('repeat_sales_count_pct',
 '% кол-во продаж (повт.)', '% прод. повт.',
 'Доля повторных продаж в общем количестве продаж (%)',
 'calculated', 'percent',
 '[repeat_sales_count] / ([primary_sales_count] + [repeat_sales_count]) * 100',
 ARRAY['repeat_sales_count','primary_sales_count'],
 1, 'avg', 'sales', 380,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['sales','repeat','percent'],
 false, true, true, false),

-- % сумма продаж повторных
('repeat_sales_amount_pct',
 '% сумма продаж (повт.)', '% сумма повт.',
 'Доля суммы повторных продаж в общей сумме продаж (%)',
 'calculated', 'percent',
 '[repeat_sales_amount] / ([primary_sales_amount] + [repeat_sales_amount]) * 100',
 ARRAY['repeat_sales_amount','primary_sales_amount'],
 1, 'avg', 'sales', 390,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['sales','repeat','percent','amount'],
 false, true, true, false),

-- ══════════════════════════════════════════════
-- 5. БРОНИ
-- ══════════════════════════════════════════════

('primary_reservations_count',
 'Кол-во броней (перв.)', 'Брони перв.',
 'Количество первичных броней за период (по дате бронирования reserved_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'reservations', 400,
 true, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'reserved_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['reservations','primary'],
 false, false, false, false),

('primary_reservations_amount',
 'Сумма броней (перв.)', 'Сумма броней',
 'Сумма первичных броней за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'reservations', 410,
 false, false, false, false,
 'deals', 'sum', 'amount', 'reserved_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['reservations','primary','amount'],
 false, false, false, false),

('primary_confirmed_count',
 'Кол-во подтв. броней (перв.)', 'Подтв. брони',
 'Количество подтверждённых первичных броней за период (по дате confirmed_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'reservations', 420,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'confirmed_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['reservations','primary','confirmed'],
 false, false, false, false),

('primary_confirmed_amount',
 'Сумма подтв. броней (перв.)', 'Сумма подтв.',
 'Сумма подтверждённых первичных броней за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'reservations', 430,
 false, false, false, false,
 'deals', 'sum', 'amount', 'confirmed_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['reservations','primary','confirmed','amount'],
 false, false, false, false),

('all_confirmed_amount',
 'Сумма подтв. броней (все)', 'Сумма подтв. все',
 'Сумма всех подтверждённых броней за период (без фильтра по воронке)',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'reservations', 440,
 false, false, false, false,
 'deals', 'sum', 'amount', 'confirmed_at', '[]'::jsonb,
 ARRAY['reservations','confirmed','amount'],
 false, false, false, false),

('primary_confirmed_avg_amount',
 'Ср. чек подтв. броней (перв.)', 'Ср. чек подтв.',
 'Средний чек подтверждённых первичных броней',
 'collected', 'money', NULL, '{}',
 0, 'avg', 'reservations', 450,
 false, false, false, false,
 'deals', 'avg', 'amount', 'confirmed_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['reservations','primary','confirmed','avg'],
 false, false, false, false),

('all_confirmed_avg_amount',
 'Ср. чек подтв. броней (все)', 'Ср. чек подтв. все',
 'Средний чек всех подтверждённых броней',
 'collected', 'money', NULL, '{}',
 0, 'avg', 'reservations', 460,
 false, false, false, false,
 'deals', 'avg', 'amount', 'confirmed_at', '[]'::jsonb,
 ARRAY['reservations','confirmed','avg'],
 false, false, false, false),

-- ══════════════════════════════════════════════
-- 6. ОТГРУЗКИ
-- ══════════════════════════════════════════════

('primary_shipments_count',
 'Кол-во отгрузок (перв.)', 'Отгр. перв.',
 'Количество первичных отгрузок за период (по дате delivered_at)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'shipments', 500,
 true, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'delivered_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['shipments','primary'],
 false, false, false, false),

('primary_shipments_amount',
 'Сумма отгрузок (перв.)', 'Сумма отгр. перв.',
 'Сумма первичных отгрузок за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'shipments', 510,
 true, false, false, false,
 'deals', 'sum', 'amount', 'delivered_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb,
 ARRAY['shipments','primary','amount'],
 false, false, false, false),

('repeat_shipments_count',
 'Кол-во отгрузок (повт.)', 'Отгр. повт.',
 'Количество повторных отгрузок за период',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'shipments', 520,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'delivered_at',
 '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb,
 ARRAY['shipments','repeat'],
 false, false, false, false),

('repeat_shipments_amount',
 'Сумма отгрузок (повт.)', 'Сумма отгр. повт.',
 'Сумма повторных отгрузок за период',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'shipments', 530,
 false, false, false, false,
 'deals', 'sum', 'amount', 'delivered_at',
 '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb,
 ARRAY['shipments','repeat','amount'],
 false, false, false, false),

-- % повторных отгрузок
('repeat_shipments_count_pct',
 '% повторных отгрузок (кол-во)', '% отгр. повт.',
 'Доля повторных отгрузок в общем количестве отгрузок (%)',
 'calculated', 'percent',
 '[repeat_shipments_count] / ([primary_shipments_count] + [repeat_shipments_count]) * 100',
 ARRAY['repeat_shipments_count','primary_shipments_count'],
 1, 'avg', 'shipments', 540,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['shipments','repeat','percent'],
 false, true, true, false),

('repeat_shipments_amount_pct',
 '% повторных отгрузок (сумма)', '% сумма отгр.',
 'Доля суммы повторных отгрузок в общей сумме отгрузок (%)',
 'calculated', 'percent',
 '[repeat_shipments_amount] / ([primary_shipments_amount] + [repeat_shipments_amount]) * 100',
 ARRAY['repeat_shipments_amount','primary_shipments_amount'],
 1, 'avg', 'shipments', 550,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['shipments','repeat','percent','amount'],
 false, true, true, false),

-- ══════════════════════════════════════════════
-- 8. КОНВЕРСИИ (CR)
-- ══════════════════════════════════════════════

('cr_deal_to_sale',
 'CR сделка/продажа (перв.)', 'CR сделка/прод.',
 'Конверсия: какой % первичных входящих сделок завершился продажей',
 'calculated', 'percent',
 '[primary_sales_count] / [primary_deals_count] * 100',
 ARRAY['primary_sales_count','primary_deals_count'],
 1, 'avg', 'cr', 600,
 true, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','sales','primary'],
 false, true, true, false),

('cr_deal_to_reservation',
 'CR сделка/брони (перв.)', 'CR сделка/бронь',
 'Конверсия: какой % первичных сделок получил бронь',
 'calculated', 'percent',
 '[primary_reservations_count] / [primary_deals_count] * 100',
 ARRAY['primary_reservations_count','primary_deals_count'],
 1, 'avg', 'cr', 610,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','reservations','primary'],
 false, true, true, false),

('cr_reservation_to_sale',
 'CR брони/продажи (перв.)', 'CR бронь/прод.',
 'Конверсия: какой % первичных броней дошёл до продажи',
 'calculated', 'percent',
 '[primary_sales_count] / [primary_reservations_count] * 100',
 ARRAY['primary_sales_count','primary_reservations_count'],
 1, 'avg', 'cr', 620,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','reservations','sales','primary'],
 false, true, true, false),

('cr_reservation_to_confirmed',
 'CR брони/подтв. брони (перв.)', 'CR бронь/подтв.',
 'Конверсия: какой % первичных броней был подтверждён',
 'calculated', 'percent',
 '[primary_confirmed_count] / [primary_reservations_count] * 100',
 ARRAY['primary_confirmed_count','primary_reservations_count'],
 1, 'avg', 'cr', 630,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','reservations','confirmed','primary'],
 false, true, true, false),

('cr_deal_to_confirmed',
 'CR сделка/подтв. брони (перв.)', 'CR сделка/подтв.',
 'Конверсия: какой % первичных сделок дошёл до подтверждённой брони',
 'calculated', 'percent',
 '[primary_confirmed_count] / [primary_deals_count] * 100',
 ARRAY['primary_confirmed_count','primary_deals_count'],
 1, 'avg', 'cr', 640,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','confirmed','primary'],
 false, true, true, false),

('cr_confirmed_to_sale',
 'CR подтв. брони/продажи (перв.)', 'CR подтв./прод.',
 'Конверсия: какой % подтверждённых первичных броней завершился продажей',
 'calculated', 'percent',
 '[primary_sales_count] / [primary_confirmed_count] * 100',
 ARRAY['primary_sales_count','primary_confirmed_count'],
 1, 'avg', 'cr', 650,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','confirmed','sales','primary'],
 false, true, true, false),

('cr_sale_to_shipment',
 'CR продажа/отгрузка', 'CR прод./отгр.',
 'Конверсия: какой % всех продаж был отгружен (первичные + повторные)',
 'calculated', 'percent',
 '([primary_shipments_count] + [repeat_shipments_count]) / ([primary_sales_count] + [repeat_sales_count]) * 100',
 ARRAY['primary_shipments_count','repeat_shipments_count','primary_sales_count','repeat_sales_count'],
 1, 'avg', 'cr', 660,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','shipments','sales'],
 false, true, true, false),

('cr_reservation_to_shipment',
 'CR брони→отгрузки (перв.)', 'CR бронь/отгр.',
 'Конверсия: какой % первичных броней дошёл до отгрузки',
 'calculated', 'percent',
 '[primary_shipments_count] / [primary_reservations_count] * 100',
 ARRAY['primary_shipments_count','primary_reservations_count'],
 1, 'avg', 'cr', 670,
 false, false, false, false,
 'deals', NULL, NULL, NULL, '[]'::jsonb,
 ARRAY['cr','reservations','shipments','primary'],
 false, true, true, false),

-- ══════════════════════════════════════════════
-- 9. СТАДИЙНЫЕ ПЕРЕХОДЫ
-- ══════════════════════════════════════════════

-- Продажа → отказ: сделки с sold_at (продавались) и lost_at в периоде
('sale_to_lost_count',
 'Продажа → отказ (кол-во)', 'Прод.→отказ',
 'Сделки, которые сначала были проданы (sold_at IS NOT NULL), а затем получили отказ (lost_at за период)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'transitions', 700,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'lost_at',
 '[{"field":"sold_at","op":"is_not_null","value":""}]'::jsonb,
 ARRAY['refusals','transitions'],
 false, false, false, false),

-- Бронь → отказ: сделки с reserved_at и lost_at в периоде
('reservation_to_lost_count',
 'Бронь → отказ (кол-во)', 'Бронь→отказ',
 'Сделки, которые были забронированы (reserved_at IS NOT NULL), а затем получили отказ (lost_at за период)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'transitions', 710,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'lost_at',
 '[{"field":"reserved_at","op":"is_not_null","value":""}]'::jsonb,
 ARRAY['refusals','transitions'],
 false, false, false, false),

-- Брони→заказ в работе: сделки с reserved_at и sold_at в периоде
('reservation_to_sale_count',
 'Брони → Заказ в работе (кол-во)', 'Бронь→продажа',
 'Сделки с бронью (reserved_at IS NOT NULL), которые перешли в продажу (sold_at за период)',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'transitions', 720,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'sold_at',
 '[{"field":"reserved_at","op":"is_not_null","value":""}]'::jsonb,
 ARRAY['transitions','reservations','sales'],
 false, false, false, false),

('reservation_to_sale_amount',
 'Брони → Заказ в работе (сумма)', 'Бронь→прод. сумма',
 'Сумма сделок с бронью, которые перешли в продажу (sold_at за период)',
 'collected', 'money', NULL, '{}',
 0, 'sum', 'transitions', 730,
 false, false, false, false,
 'deals', 'sum', 'amount', 'sold_at',
 '[{"field":"reserved_at","op":"is_not_null","value":""}]'::jsonb,
 ARRAY['transitions','reservations','sales','amount'],
 false, false, false, false),

-- ══════════════════════════════════════════════
-- 10. СДЕЛКИ — ПРОЧИЕ
-- ══════════════════════════════════════════════

-- Необработанные: текущая стадия = начальная (event_type='new')
('unprocessed_primary_count',
 'Кол-во необр. сделок (перв.)', 'Необр. перв.',
 'Первичные сделки в начальной стадии (event_type=''new''), созданные за период',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'deals', 800,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'created_at',
 '[{"field":"funnel_type","op":"eq","value":"primary"},{"field":"stage_type","op":"eq","value":"new"}]'::jsonb,
 ARRAY['deals','primary','unprocessed'],
 false, false, false, false),

('unprocessed_repeat_count',
 'Кол-во необр. сделок (повт.)', 'Необр. повт.',
 'Повторные сделки в начальной стадии (event_type=''new''), созданные за период',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'deals', 810,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'created_at',
 '[{"field":"funnel_type","op":"eq","value":"repeat"},{"field":"stage_type","op":"eq","value":"new"}]'::jsonb,
 ARRAY['deals','repeat','unprocessed'],
 false, false, false, false),

-- Без товаров
('no_products_count',
 'Без товаров', 'Без товаров',
 'Сделки без привязанных товаров (products пустой или NULL), созданные за период',
 'collected', 'int', NULL, '{}',
 0, 'sum', 'deals', 820,
 false, false, false, false,
 'deals', 'count_distinct', 'deal_id', 'created_at',
 '[{"field":"products","op":"is_null","value":""}]'::jsonb,
 ARRAY['deals','quality'],
 false, false, false, false)

ON CONFLICT (id) DO NOTHING;
