-- Seed main report for junior user
INSERT INTO saved_reports (
  user_login, report_slug, name, metric_ids,
  deal_scope, client_type, grouping, comparison_display, product_group_mode,
  department_ids, metric_highlights, metric_display_modes, comparison_threshold,
  period_mode, relative_period, comparison_mode
) VALUES (
  'junior',
  'by-managers',
  'Основной отчёт',
  ARRAY[
    'primary_deals_count',
    'called_deals_count',
    'primary_reservations_count',
    'primary_confirmed_count',
    'cr_deal_to_reservation',
    'cr_deal_to_confirmed',
    'primary_sales_count',
    'cr_reservation_to_sale',
    'cr_confirmed_to_sale',
    'cr_deal_to_sale',
    'primary_shipments_count',
    'cr_deal_to_shipment',
    'plan_sales_month',
    'primary_sales_amount',
    'repeat_sales_amount',
    'all_sales_amount',
    'plan_execution_pct',
    'repeat_sales_count_pct',
    'primary_sales_avg_amount',
    'repeat_shipments_count',
    'ppp_count',
    'ppp_conversion',
    'ppp_amount',
    'repeat_created_count',
    'repeat_sales_count',
    'cr_primary_to_repeat_created',
    'cr_repeat_created_to_sale'
  ],
  'all',
  'all',
  'none',
  'full',
  'kc',
  '{}',
  '{}',
  '{}',
  5,
  'relative',
  '{"unit":"month","value":0}'::jsonb,
  'previous_period'
);
