-- Единый нейминг метрик + полные тройки (перв./повт./все).
-- Правила: см. память metric-naming-rules + WORKLOG 2026-07-02. id существующих не меняются.
-- БД: YC analytics (run_analytics.mjs).

UPDATE metrics SET name_ru = 'Кол-во сделок (перв.)', category = 'Сделки', sort_order = 100 WHERE id = 'primary_deals_count';
UPDATE metrics SET name_ru = 'Кол-во сделок (повт.)', category = 'Сделки', sort_order = 101 WHERE id = 'repeat_created_count';
UPDATE metrics SET name_ru = 'Сумма сделок (перв.)', category = 'Сделки', sort_order = 103 WHERE id = 'primary_deals_amount';
UPDATE metrics SET name_ru = 'Ср. чек сделок (перв.)', category = 'Сделки', sort_order = 106 WHERE id = 'primary_deals_avg_amount';
UPDATE metrics SET name_ru = 'Кол-во необраб. сделок (перв.)', category = 'Сделки', sort_order = 110 WHERE id = 'unprocessed_primary_count';
UPDATE metrics SET name_ru = 'Кол-во необраб. сделок (повт.)', category = 'Сделки', sort_order = 111 WHERE id = 'unprocessed_repeat_count';
UPDATE metrics SET name_ru = 'Кол-во сделок без товаров', category = 'Сделки', sort_order = 115 WHERE id = 'no_products_count';
UPDATE metrics SET name_ru = 'Кол-во броней (перв.)', category = 'Брони', sort_order = 200 WHERE id = 'primary_reservations_count';
UPDATE metrics SET name_ru = 'Кол-во броней (повт.)', category = 'Брони', sort_order = 201 WHERE id = 'repeat_reservations_count';
UPDATE metrics SET name_ru = 'Кол-во броней', category = 'Брони', sort_order = 202 WHERE id = 'reservations_count';
UPDATE metrics SET name_ru = 'Сумма броней (перв.)', category = 'Брони', sort_order = 203 WHERE id = 'primary_reservations_amount';
UPDATE metrics SET name_ru = 'Кол-во подтв. броней (перв.)', category = 'Брони', sort_order = 210 WHERE id = 'primary_confirmed_count';
UPDATE metrics SET name_ru = 'Кол-во подтв. броней (повт.)', category = 'Брони', sort_order = 211 WHERE id = 'repeat_confirmed_count';
UPDATE metrics SET name_ru = 'Кол-во подтв. броней', category = 'Брони', sort_order = 212 WHERE id = 'confirmed_reservations_count';
UPDATE metrics SET name_ru = 'Сумма подтв. броней (перв.)', category = 'Брони', sort_order = 213 WHERE id = 'primary_confirmed_amount';
UPDATE metrics SET name_ru = 'Сумма подтв. броней', category = 'Брони', sort_order = 215 WHERE id = 'all_confirmed_amount';
UPDATE metrics SET name_ru = 'Ср. чек подтв. броней (перв.)', category = 'Брони', sort_order = 216 WHERE id = 'primary_confirmed_avg_amount';
UPDATE metrics SET name_ru = 'Ср. чек подтв. броней', category = 'Брони', sort_order = 218 WHERE id = 'all_confirmed_avg_amount';
UPDATE metrics SET name_ru = 'Кол-во продаж (перв.)', category = 'Продажи', sort_order = 300 WHERE id = 'primary_sales_count';
UPDATE metrics SET name_ru = 'Кол-во продаж (повт.)', category = 'Продажи', sort_order = 301 WHERE id = 'repeat_sales_count';
UPDATE metrics SET name_ru = 'Кол-во продаж', category = 'Продажи', sort_order = 302 WHERE id = 'sales_count';
UPDATE metrics SET name_ru = 'Сумма продаж (перв.)', category = 'Продажи', sort_order = 303 WHERE id = 'primary_sales_amount';
UPDATE metrics SET name_ru = 'Сумма продаж (повт.)', category = 'Продажи', sort_order = 304 WHERE id = 'repeat_sales_amount';
UPDATE metrics SET name_ru = 'Сумма продаж', category = 'Продажи', sort_order = 305 WHERE id = 'all_sales_amount';
UPDATE metrics SET name_ru = 'Ср. чек продаж (перв.)', category = 'Продажи', sort_order = 306 WHERE id = 'primary_sales_avg_amount';
UPDATE metrics SET name_ru = 'Ср. чек продаж', category = 'Продажи', sort_order = 308 WHERE id = 'all_sales_avg_amount';
UPDATE metrics SET name_ru = 'Кол-во продаж из брони', category = 'Продажи', sort_order = 312 WHERE id = 'reservation_to_sale_count';
UPDATE metrics SET name_ru = 'Сумма продаж из брони', category = 'Продажи', sort_order = 315 WHERE id = 'reservation_to_sale_amount';
UPDATE metrics SET name_ru = 'Кол-во продаж из подтв. брони (перв.)', category = 'Продажи', sort_order = 316, is_hidden_in_ui = false WHERE id = 'primary_confirmed_sales_count';
UPDATE metrics SET name_ru = 'Доля повторных продаж, % (кол-во)', category = 'Продажи', sort_order = 330 WHERE id = 'repeat_sales_count_pct';
UPDATE metrics SET name_ru = 'Доля повторных продаж, % (сумма)', category = 'Продажи', sort_order = 331 WHERE id = 'repeat_sales_amount_pct';
UPDATE metrics SET name_ru = 'ППП', category = 'Продажи', sort_order = 340 WHERE id = 'ppp_count';
UPDATE metrics SET name_ru = 'Сумма ППП', category = 'Продажи', sort_order = 341 WHERE id = 'ppp_amount';
UPDATE metrics SET name_ru = 'CR ППП', category = 'Продажи', sort_order = 342 WHERE id = 'ppp_conversion';
UPDATE metrics SET name_ru = 'Кол-во отгрузок (перв.)', category = 'Отгрузки', sort_order = 400 WHERE id = 'primary_shipments_count';
UPDATE metrics SET name_ru = 'Кол-во отгрузок (повт.)', category = 'Отгрузки', sort_order = 401 WHERE id = 'repeat_shipments_count';
UPDATE metrics SET name_ru = 'Кол-во отгрузок', category = 'Отгрузки', sort_order = 402 WHERE id = 'shipments_count';
UPDATE metrics SET name_ru = 'Сумма отгрузок (перв.)', category = 'Отгрузки', sort_order = 403 WHERE id = 'primary_shipments_amount';
UPDATE metrics SET name_ru = 'Сумма отгрузок (повт.)', category = 'Отгрузки', sort_order = 404 WHERE id = 'repeat_shipments_amount';
UPDATE metrics SET name_ru = 'Ср. чек отгрузок (перв.)', category = 'Отгрузки', sort_order = 406 WHERE id = 'primary_shipments_avg_amount';
UPDATE metrics SET name_ru = 'Ср. чек отгрузок', category = 'Отгрузки', sort_order = 408 WHERE id = 'all_shipments_avg_amount';
UPDATE metrics SET name_ru = 'Доля повторных отгрузок, % (кол-во)', category = 'Отгрузки', sort_order = 410 WHERE id = 'repeat_shipments_count_pct';
UPDATE metrics SET name_ru = 'Доля повторных отгрузок, % (сумма)', category = 'Отгрузки', sort_order = 411 WHERE id = 'repeat_shipments_amount_pct';
UPDATE metrics SET name_ru = 'ППО', category = 'Отгрузки', sort_order = 420 WHERE id = 'ppo_count';
UPDATE metrics SET name_ru = 'Сумма ППО', category = 'Отгрузки', sort_order = 421 WHERE id = 'ppo_amount';
UPDATE metrics SET name_ru = 'CR ППО', category = 'Отгрузки', sort_order = 422 WHERE id = 'ppo_conversion';
UPDATE metrics SET name_ru = 'CR Сделка → Бронь (перв.)', category = 'Конверсии', sort_order = 500 WHERE id = 'cr_deal_to_reservation';
UPDATE metrics SET name_ru = 'CR Сделка → Подтв. бронь (перв.)', category = 'Конверсии', sort_order = 503 WHERE id = 'cr_deal_to_confirmed';
UPDATE metrics SET name_ru = 'CR Сделка → Продажа (перв.)', category = 'Конверсии', sort_order = 506 WHERE id = 'cr_deal_to_sale';
UPDATE metrics SET name_ru = 'CR Сделка → Продажа (повт.)', category = 'Конверсии', sort_order = 507 WHERE id = 'cr_repeat_created_to_sale';
UPDATE metrics SET name_ru = 'CR Сделка → Отгрузка (перв.)', category = 'Конверсии', sort_order = 509 WHERE id = 'cr_deal_to_shipment';
UPDATE metrics SET name_ru = 'CR Бронь → Подтв. бронь (перв.)', category = 'Конверсии', sort_order = 512 WHERE id = 'cr_reservation_to_confirmed';
UPDATE metrics SET name_ru = 'CR Бронь → Продажа (перв.)', category = 'Конверсии', sort_order = 515 WHERE id = 'cr_reservation_to_sale';
UPDATE metrics SET name_ru = 'CR Бронь → Отгрузка (перв.)', category = 'Конверсии', sort_order = 518 WHERE id = 'cr_reservation_to_shipment';
UPDATE metrics SET name_ru = 'CR Подтв. бронь → Продажа (перв.)', category = 'Конверсии', sort_order = 521 WHERE id = 'cr_confirmed_to_sale';
UPDATE metrics SET name_ru = 'CR Продажа → Отгрузка', category = 'Конверсии', sort_order = 526 WHERE id = 'cr_sale_to_shipment';
UPDATE metrics SET name_ru = 'CR Продажа → Повт. сделка', category = 'Конверсии', sort_order = 530 WHERE id = 'cr_primary_to_repeat_created';
UPDATE metrics SET name_ru = 'Кол-во отказов', category = 'Отказы', sort_order = 602, is_active = true WHERE id = 'lost_deals_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из брони (перв.)', category = 'Отказы', sort_order = 610 WHERE id = 'primary_reservation_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из брони (повт.)', category = 'Отказы', sort_order = 611 WHERE id = 'repeat_reservation_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из брони', category = 'Отказы', sort_order = 612 WHERE id = 'reservation_to_lost_count';
UPDATE metrics SET name_ru = 'Сумма отказов из брони (перв.)', category = 'Отказы', sort_order = 613 WHERE id = 'primary_reservation_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из брони (повт.)', category = 'Отказы', sort_order = 614 WHERE id = 'repeat_reservation_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из брони', category = 'Отказы', sort_order = 615 WHERE id = 'reservation_to_lost_amount';
UPDATE metrics SET name_ru = 'Кол-во отказов из подтв. брони (перв.)', category = 'Отказы', sort_order = 620 WHERE id = 'primary_confirmed_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из подтв. брони (повт.)', category = 'Отказы', sort_order = 621 WHERE id = 'repeat_confirmed_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из подтв. брони', category = 'Отказы', sort_order = 622 WHERE id = 'confirmed_to_lost_count';
UPDATE metrics SET name_ru = 'Сумма отказов из подтв. брони (перв.)', category = 'Отказы', sort_order = 623 WHERE id = 'primary_confirmed_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из подтв. брони (повт.)', category = 'Отказы', sort_order = 624 WHERE id = 'repeat_confirmed_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из подтв. брони', category = 'Отказы', sort_order = 625 WHERE id = 'confirmed_to_lost_amount';
UPDATE metrics SET name_ru = 'Кол-во отказов из продажи (перв.)', category = 'Отказы', sort_order = 630 WHERE id = 'primary_sale_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из продажи (повт.)', category = 'Отказы', sort_order = 631 WHERE id = 'repeat_sale_to_lost_count';
UPDATE metrics SET name_ru = 'Кол-во отказов из продажи', category = 'Отказы', sort_order = 632 WHERE id = 'sale_to_lost_count';
UPDATE metrics SET name_ru = 'Сумма отказов из продажи (перв.)', category = 'Отказы', sort_order = 633 WHERE id = 'primary_sale_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из продажи (повт.)', category = 'Отказы', sort_order = 634 WHERE id = 'repeat_sale_to_lost_amount';
UPDATE metrics SET name_ru = 'Сумма отказов из продажи', category = 'Отказы', sort_order = 635 WHERE id = 'sale_to_lost_amount';
UPDATE metrics SET name_ru = 'CR Бронь → Отказ (перв.)', category = 'Отказы', sort_order = 640 WHERE id = 'cr_reservation_to_lost_primary';
UPDATE metrics SET name_ru = 'CR Бронь → Отказ (повт.)', category = 'Отказы', sort_order = 641 WHERE id = 'cr_reservation_to_lost_repeat';
UPDATE metrics SET name_ru = 'CR Бронь → Отказ', category = 'Отказы', sort_order = 642 WHERE id = 'cr_reservation_to_lost_all';
UPDATE metrics SET name_ru = 'CR Подтв. бронь → Отказ (перв.)', category = 'Отказы', sort_order = 643 WHERE id = 'cr_confirmed_to_lost_primary';
UPDATE metrics SET name_ru = 'CR Подтв. бронь → Отказ (повт.)', category = 'Отказы', sort_order = 644 WHERE id = 'cr_confirmed_to_lost_repeat';
UPDATE metrics SET name_ru = 'CR Подтв. бронь → Отказ', category = 'Отказы', sort_order = 645 WHERE id = 'cr_confirmed_to_lost_all';
UPDATE metrics SET name_ru = 'CR Продажа → Отказ (перв.)', category = 'Отказы', sort_order = 646 WHERE id = 'cr_sale_to_lost_primary';
UPDATE metrics SET name_ru = 'CR Продажа → Отказ (повт.)', category = 'Отказы', sort_order = 647 WHERE id = 'cr_sale_to_lost_repeat';
UPDATE metrics SET name_ru = 'CR Продажа → Отказ', category = 'Отказы', sort_order = 648 WHERE id = 'cr_sale_to_lost_all';
UPDATE metrics SET name_ru = 'План продаж (месяц)', category = 'Планы', sort_order = 800 WHERE id = 'plan_sales_month';
UPDATE metrics SET name_ru = 'План отгрузок (месяц)', category = 'Планы', sort_order = 801 WHERE id = 'plan_shipments_month';
UPDATE metrics SET name_ru = 'План продаж (на сегодня)', category = 'Планы', sort_order = 802 WHERE id = 'plan_sales_today';
UPDATE metrics SET name_ru = 'План отгрузок (на сегодня)', category = 'Планы', sort_order = 803 WHERE id = 'plan_shipments_today';
UPDATE metrics SET name_ru = 'Исполнение плана, %', category = 'Планы', sort_order = 804 WHERE id = 'plan_execution_pct';
UPDATE metrics SET name_ru = 'Изменено сделок', category = 'Прочее', sort_order = 900 WHERE id = 'changed_deals_count';

-- Новые collected
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('deals_count', 'Кол-во сделок', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'created_at', '[]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Сделки', 102)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_deals_amount', 'Сумма сделок (повт.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'created_at', '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Сделки', 104)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('deals_amount', 'Сумма сделок', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'created_at', '[]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Сделки', 105)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('unprocessed_count', 'Кол-во необраб. сделок', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'created_at', '[{"field":"stage_type","op":"eq","value":"new"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Сделки', 112)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_reservations_amount', 'Сумма броней (повт.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'reserved_at', '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Брони', 204)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('reservations_amount', 'Сумма броней', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'reserved_at', '[]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Брони', 205)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_confirmed_amount', 'Сумма подтв. броней (повт.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'confirmed_at', '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Брони', 214)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('primary_reservation_to_sale_count', 'Кол-во продаж из брони (перв.)', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'sold_at', '[{"field":"reserved_at","op":"is_not_null","value":""},{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 310)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_reservation_to_sale_count', 'Кол-во продаж из брони (повт.)', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'sold_at', '[{"field":"reserved_at","op":"is_not_null","value":""},{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 311)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('primary_reservation_to_sale_amount', 'Сумма продаж из брони (перв.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'sold_at', '[{"field":"reserved_at","op":"is_not_null","value":""},{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 313)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_reservation_to_sale_amount', 'Сумма продаж из брони (повт.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'sold_at', '[{"field":"reserved_at","op":"is_not_null","value":""},{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 314)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_confirmed_sales_count', 'Кол-во продаж из подтв. брони (повт.)', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'sold_at', '[{"field":"confirmed_at","op":"is_not_null","value":""},{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 317)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('confirmed_sales_count', 'Кол-во продаж из подтв. брони', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'sold_at', '[{"field":"confirmed_at","op":"is_not_null","value":""}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Продажи', 318)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('shipments_amount', 'Сумма отгрузок', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'delivered_at', '[]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отгрузки', 405)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('primary_lost_deals_count', 'Кол-во отказов (перв.)', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'lost_at', '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отказы', 600)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_lost_deals_count', 'Кол-во отказов (повт.)', NULL, 'collected', 'int', 'deals', 'count_distinct', 'deal_id', 'lost_at', '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отказы', 601)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('primary_lost_deals_amount', 'Сумма отказов (перв.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'lost_at', '[{"field":"funnel_type","op":"eq","value":"primary"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отказы', 603)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_lost_deals_amount', 'Сумма отказов (повт.)', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'lost_at', '[{"field":"funnel_type","op":"eq","value":"repeat"}]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отказы', 604)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, source, agg_fn, agg_field, date_field, filters, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('lost_deals_amount', 'Сумма отказов', NULL, 'collected', 'money', 'deals', 'sum', 'amount', 'lost_at', '[]'::jsonb, '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Отказы', 605)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, filters = EXCLUDED.filters, date_field = EXCLUDED.date_field, agg_fn = EXCLUDED.agg_fn, agg_field = EXCLUDED.agg_field, is_active = EXCLUDED.is_active;

-- Новые calculated
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_deals_avg_amount', 'Ср. чек сделок (повт.)', NULL, 'calculated', 'money', '[repeat_deals_amount] / [repeat_created_count]', ARRAY['repeat_deals_amount','repeat_created_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Сделки', 107)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('deals_avg_amount', 'Ср. чек сделок', NULL, 'calculated', 'money', '[deals_amount] / [deals_count]', ARRAY['deals_amount','deals_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Сделки', 108)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('primary_reservations_avg_amount', 'Ср. чек броней (перв.)', NULL, 'calculated', 'money', '[primary_reservations_amount] / [primary_reservations_count]', ARRAY['primary_reservations_amount','primary_reservations_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Брони', 206)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_reservations_avg_amount', 'Ср. чек броней (повт.)', NULL, 'calculated', 'money', '[repeat_reservations_amount] / [repeat_reservations_count]', ARRAY['repeat_reservations_amount','repeat_reservations_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Брони', 207)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('reservations_avg_amount', 'Ср. чек броней', NULL, 'calculated', 'money', '[reservations_amount] / [reservations_count]', ARRAY['reservations_amount','reservations_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Брони', 208)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_confirmed_avg_amount', 'Ср. чек подтв. броней (повт.)', NULL, 'calculated', 'money', '[repeat_confirmed_amount] / [repeat_confirmed_count]', ARRAY['repeat_confirmed_amount','repeat_confirmed_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Брони', 217)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_sales_avg_amount', 'Ср. чек продаж (повт.)', NULL, 'calculated', 'money', '[repeat_sales_amount] / [repeat_sales_count]', ARRAY['repeat_sales_amount','repeat_sales_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Продажи', 307)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('repeat_shipments_avg_amount', 'Ср. чек отгрузок (повт.)', NULL, 'calculated', 'money', '[repeat_shipments_amount] / [repeat_shipments_count]', ARRAY['repeat_shipments_amount','repeat_shipments_count'], '{}', false, true, false, false, 0, 'avg', false, true, false, true, 'Отгрузки', 407)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_reservation_repeat', 'CR Сделка → Бронь (повт.)', NULL, 'calculated', 'percent', '[repeat_reservations_count] / [repeat_created_count] * 100', ARRAY['repeat_reservations_count','repeat_created_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 501)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_reservation_all', 'CR Сделка → Бронь', NULL, 'calculated', 'percent', '[reservations_count] / [deals_count] * 100', ARRAY['reservations_count','deals_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 502)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_confirmed_repeat', 'CR Сделка → Подтв. бронь (повт.)', NULL, 'calculated', 'percent', '[repeat_confirmed_count] / [repeat_created_count] * 100', ARRAY['repeat_confirmed_count','repeat_created_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 504)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_confirmed_all', 'CR Сделка → Подтв. бронь', NULL, 'calculated', 'percent', '[confirmed_reservations_count] / [deals_count] * 100', ARRAY['confirmed_reservations_count','deals_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 505)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_sale_all', 'CR Сделка → Продажа', NULL, 'calculated', 'percent', '[sales_count] / [deals_count] * 100', ARRAY['sales_count','deals_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 508)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_shipment_repeat', 'CR Сделка → Отгрузка (повт.)', NULL, 'calculated', 'percent', '[repeat_shipments_count] / [repeat_created_count] * 100', ARRAY['repeat_shipments_count','repeat_created_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 510)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_deal_to_shipment_all', 'CR Сделка → Отгрузка', NULL, 'calculated', 'percent', '[shipments_count] / [deals_count] * 100', ARRAY['shipments_count','deals_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 511)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_confirmed_repeat', 'CR Бронь → Подтв. бронь (повт.)', NULL, 'calculated', 'percent', '[repeat_confirmed_count] / [repeat_reservations_count] * 100', ARRAY['repeat_confirmed_count','repeat_reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 513)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_confirmed_all', 'CR Бронь → Подтв. бронь', NULL, 'calculated', 'percent', '[confirmed_reservations_count] / [reservations_count] * 100', ARRAY['confirmed_reservations_count','reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 514)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_sale_repeat', 'CR Бронь → Продажа (повт.)', NULL, 'calculated', 'percent', '[repeat_sales_count] / [repeat_reservations_count] * 100', ARRAY['repeat_sales_count','repeat_reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 516)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_sale_all', 'CR Бронь → Продажа', NULL, 'calculated', 'percent', '[sales_count] / [reservations_count] * 100', ARRAY['sales_count','reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 517)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_shipment_repeat', 'CR Бронь → Отгрузка (повт.)', NULL, 'calculated', 'percent', '[repeat_shipments_count] / [repeat_reservations_count] * 100', ARRAY['repeat_shipments_count','repeat_reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 519)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_reservation_to_shipment_all', 'CR Бронь → Отгрузка', NULL, 'calculated', 'percent', '[shipments_count] / [reservations_count] * 100', ARRAY['shipments_count','reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 520)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_confirmed_to_sale_repeat', 'CR Подтв. бронь → Продажа (повт.)', NULL, 'calculated', 'percent', '[repeat_confirmed_sales_count] / [repeat_confirmed_count] * 100', ARRAY['repeat_confirmed_sales_count','repeat_confirmed_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 522)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_confirmed_to_sale_all', 'CR Подтв. бронь → Продажа', NULL, 'calculated', 'percent', '[confirmed_sales_count] / [confirmed_reservations_count] * 100', ARRAY['confirmed_sales_count','confirmed_reservations_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 523)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_sale_to_shipment_primary', 'CR Продажа → Отгрузка (перв.)', NULL, 'calculated', 'percent', '[primary_shipments_count] / [primary_sales_count] * 100', ARRAY['primary_shipments_count','primary_sales_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 524)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order)
VALUES ('cr_sale_to_shipment_repeat', 'CR Продажа → Отгрузка (повт.)', NULL, 'calculated', 'percent', '[repeat_shipments_count] / [repeat_sales_count] * 100', ARRAY['repeat_shipments_count','repeat_sales_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Конверсии', 525)
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_active = EXCLUDED.is_active;
