-- КОЛСТАТ — метрики каталога категории «Звонки» (va.calls, та же MLT-БД, что sa.deals),
-- задача от 10.07 (owners-inbox, Николай). Разрез — МЕНЕДЖЕРЫ.
-- БД: YC analytics (таблица metrics, run_analytics.mjs). НЕ применять локально —
-- накатывает Артём на проде (атомарно, одним запросом).
--
-- Реализация: features/reports/engine/callsMetrics.ts (4 агрегатных SQL-запроса,
-- GROUPING SETS ((manager_id,is_repeat),(manager_id)) — «(все)» считается ТОЙ ЖЕ
-- группировкой, без второго прохода по va.calls). Инжектится сервером
-- app/api/reports/run/route.ts, ТОЛЬКО в отчёт «по менеджерам» (тот же приём, что
-- managerActivity.ts/stageConversions.ts).
--
-- Троица (перв.)/(повт.)/(все) — по funnels.is_repeat СВЯЗАННОЙ СДЕЛКИ звонка;
-- «сироты» (звонок без deal_id/со ссылкой на несуществующую сделку — сейчас 0 из
-- 197 488, живой запрос 10.07, join coverage 100%) попадают ТОЛЬКО в «(все)».
-- Длительности считаются ТОЛЬКО по result='completed'. Данные va.calls — с
-- 30.03.2026 (CALLS_DATA_START) — если период целиком раньше, сервер отдаёт
-- честный null (не 0).
--
-- Привязка к периоду: метрики 1-5, 9 — по called_at звонка в периоде; метрики
-- 6-8, 10 — по сделкам, СОЗДАННЫМ в периоде (created_at); метрика 11 — снимок
-- НА КОНЕЦ периода (period.to), не привязана к дате создания сделки.
--
-- Метрика 7 (скорость первого касания) переиспользует расчёт, который раньше жил
-- только в карточке менеджера (features/manager-card/engine/managerCard.ts) —
-- вынесен в callsMetrics.ts, карточка менеджера теперь дёргает ту же функцию.

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_count', 'Кол-во звонков (перв.)', 'Звонки (п)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1100, 'Кол-во звонков менеджера за период (любой результат, called_at в периоде), funnels.is_repeat=false связанной сделки. Атрибуция — va.calls.manager_id. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_count_repeat', 'Кол-во звонков (повт.)', 'Звонки (пв)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1101, 'Кол-во звонков менеджера за период (любой результат, called_at в периоде), funnels.is_repeat=true связанной сделки. Атрибуция — va.calls.manager_id. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_count_all', 'Кол-во звонков (все)', 'Звонки (вс)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1102, 'Кол-во звонков менеджера за период (любой результат, called_at в периоде), включая звонки без привязки к сделке («сироты», если появятся). Атрибуция — va.calls.manager_id. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_out', 'Длительность исходящих, мин (перв.)', 'Дл.исх (п)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1103, 'Сумма duration_seconds/60 звонков direction=''outbound'' AND result=''completed'' (перв.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_out_repeat', 'Длительность исходящих, мин (повт.)', 'Дл.исх (пв)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1104, 'Сумма duration_seconds/60 звонков direction=''outbound'' AND result=''completed'' (повт.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_out_all', 'Длительность исходящих, мин (все)', 'Дл.исх (вс)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1105, 'Сумма duration_seconds/60 звонков direction=''outbound'' AND result=''completed'' (все). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_in', 'Длительность входящих, мин (перв.)', 'Дл.вх (п)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1106, 'Сумма duration_seconds/60 звонков direction=''inbound'' AND result=''completed'' (перв.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_in_repeat', 'Длительность входящих, мин (повт.)', 'Дл.вх (пв)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1107, 'Сумма duration_seconds/60 звонков direction=''inbound'' AND result=''completed'' (повт.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_duration_in_all', 'Длительность входящих, мин (все)', 'Дл.вх (вс)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'sum', false, false, true, false, 'Звонки', 1108, 'Сумма duration_seconds/60 звонков direction=''inbound'' AND result=''completed'' (все). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_duration_sum', 'Сумма длительности завершённых разговоров, мин, перв. (служебная)', NULL, 'external', 'decimal', NULL, '{}', '{}', false, true, true, false, 1, 'sum', false, false, false, false, 'Звонки', 1109, 'Числитель средней длительности разговора (метрика 4), перв.. Служебная — не показывается в каталоге. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_duration_sum_repeat', 'Сумма длительности завершённых разговоров, мин, повт. (служебная)', NULL, 'external', 'decimal', NULL, '{}', '{}', false, true, true, false, 1, 'sum', false, false, false, false, 'Звонки', 1110, 'Числитель средней длительности разговора (метрика 4), повт.. Служебная — не показывается в каталоге. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_duration_sum_orphan', 'Сумма длительности завершённых разговоров, мин, сироты (служебная)', NULL, 'external', 'decimal', NULL, '{}', '{}', false, true, true, false, 1, 'sum', false, false, false, false, 'Звонки', 1111, 'Числитель средней длительности разговора (метрика 4), сироты. Служебная — не показывается в каталоге. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_count', 'Кол-во завершённых разговоров, перв. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1112, 'Знаменатель средней длительности разговора (метрика 4), перв.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_count_repeat', 'Кол-во завершённых разговоров, повт. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1113, 'Знаменатель средней длительности разговора (метрика 4), повт.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_completed_count_orphan', 'Кол-во завершённых разговоров, сироты (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1114, 'Знаменатель средней длительности разговора (метрика 4), сироты. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_avg_duration', 'Средняя длительность разговора, мин (перв.)', 'Ср.дл (п)', 'calculated', 'decimal', '[calls_completed_duration_sum] / [calls_completed_count]', ARRAY['calls_completed_duration_sum', 'calls_completed_count'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1115, 'Средняя длительность completed-разговора (обе стороны), мин, (перв.). = сумма/кол-во (весовое среднее, честный пересчёт в «Итого»). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_avg_duration_repeat', 'Средняя длительность разговора, мин (повт.)', 'Ср.дл (пв)', 'calculated', 'decimal', '[calls_completed_duration_sum_repeat] / [calls_completed_count_repeat]', ARRAY['calls_completed_duration_sum_repeat', 'calls_completed_count_repeat'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1116, 'Средняя длительность completed-разговора (обе стороны), мин, (повт.). = сумма/кол-во (весовое среднее, честный пересчёт в «Итого»). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_avg_duration_all', 'Средняя длительность разговора, мин (все)', 'Ср.дл (вс)', 'calculated', 'decimal', '([calls_completed_duration_sum] + [calls_completed_duration_sum_repeat] + [calls_completed_duration_sum_orphan]) / ([calls_completed_count] + [calls_completed_count_repeat] + [calls_completed_count_orphan])', ARRAY['calls_completed_duration_sum', 'calls_completed_duration_sum_repeat', 'calls_completed_duration_sum_orphan', 'calls_completed_count', 'calls_completed_count_repeat', 'calls_completed_count_orphan'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1117, 'Средняя длительность completed-разговора (обе стороны), мин, (все). = сумма/кол-во (весовое среднее, честный пересчёт в «Итого»). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_median_duration', 'Медианная длительность разговора, мин (перв.)', 'Мед.дл (п)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1118, 'Медиана (percentile_cont) duration_seconds/60 completed-звонков (перв.). Не суммируется в «Итого» (медиана медиан не имеет смысла) — честный null, как manager_attendance_pct. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_median_duration_repeat', 'Медианная длительность разговора, мин (повт.)', 'Мед.дл (пв)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1119, 'Медиана (percentile_cont) duration_seconds/60 completed-звонков (повт.). Не суммируется в «Итого» (медиана медиан не имеет смысла) — честный null, как manager_attendance_pct. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_median_duration_all', 'Медианная длительность разговора, мин (все)', 'Мед.дл (вс)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1120, 'Медиана (percentile_cont) duration_seconds/60 completed-звонков (все). Не суммируется в «Итого» (медиана медиан не имеет смысла) — честный null, как manager_attendance_pct. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_first_call_duration_median', 'Длительность первого разговора сделки, мин, медиана (перв.)', 'Дл.1зв (п)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1121, 'Медиана длительности ПЕРВОГО completed-звонка по сделкам, созданным в периоде, (перв.). Атрибуция — d.current_manager_id. Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_first_call_duration_median_repeat', 'Длительность первого разговора сделки, мин, медиана (повт.)', 'Дл.1зв (пв)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1122, 'Медиана длительности ПЕРВОГО completed-звонка по сделкам, созданным в периоде, (повт.). Атрибуция — d.current_manager_id. Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_first_call_duration_median_all', 'Длительность первого разговора сделки, мин, медиана (все)', 'Дл.1зв (вс)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1123, 'Медиана длительности ПЕРВОГО completed-звонка по сделкам, созданным в периоде, (все). Атрибуция — d.current_manager_id. Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_touch_speed_median', 'Скорость первого касания, мин, медиана (перв.)', 'Скор.1кас (п)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1124, 'Медиана (created_at сделки → первый completed-звонок), мин, по сделкам, созданным в периоде, (перв.). Атрибуция — d.current_manager_id. Тот же расчёт, что и в карточке менеджера (features/reports/engine/callsMetrics.ts, переиспользуется). Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_touch_speed_median_repeat', 'Скорость первого касания, мин, медиана (повт.)', 'Скор.1кас (пв)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1125, 'Медиана (created_at сделки → первый completed-звонок), мин, по сделкам, созданным в периоде, (повт.). Атрибуция — d.current_manager_id. Тот же расчёт, что и в карточке менеджера (features/reports/engine/callsMetrics.ts, переиспользуется). Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_touch_speed_median_all', 'Скорость первого касания, мин, медиана (все)', 'Скор.1кас (вс)', 'external', 'decimal', NULL, '{}', '{}', false, true, false, false, 1, 'none', false, false, true, false, 'Звонки', 1126, 'Медиана (created_at сделки → первый completed-звонок), мин, по сделкам, созданным в периоде, (все). Атрибуция — d.current_manager_id. Тот же расчёт, что и в карточке менеджера (features/reports/engine/callsMetrics.ts, переиспользуется). Не суммируется в «Итого». Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_num', 'Звонков от создания до брони, сумма, перв. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1127, 'Числитель «Звонков до брони» (метрика 8): сумма completed-звонков от created_at до reserved_at включительно, по сделкам с бронью, созданным в периоде, перв.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_num_repeat', 'Звонков от создания до брони, сумма, повт. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1128, 'Числитель «Звонков до брони» (метрика 8): сумма completed-звонков от created_at до reserved_at включительно, по сделкам с бронью, созданным в периоде, повт.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_denom', 'Сделок с бронью в периоде, перв. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1129, 'Знаменатель «Звонков до брони» (метрика 8): кол-во сделок, созданных в периоде, с заполненным reserved_at, перв.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_denom_repeat', 'Сделок с бронью в периоде, повт. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1130, 'Знаменатель «Звонков до брони» (метрика 8): кол-во сделок, созданных в периоде, с заполненным reserved_at, повт.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_avg', 'Звонков до брони, среднее (перв.)', 'Зв.до брони (п)', 'calculated', 'decimal', '[calls_to_reservation_num] / [calls_to_reservation_denom]', ARRAY['calls_to_reservation_num', 'calls_to_reservation_denom'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1131, 'Среднее кол-во completed-звонков от создания сделки до брони (только сделки с бронью, созданные в периоде), (перв.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_avg_repeat', 'Звонков до брони, среднее (повт.)', 'Зв.до брони (пв)', 'calculated', 'decimal', '[calls_to_reservation_num_repeat] / [calls_to_reservation_denom_repeat]', ARRAY['calls_to_reservation_num_repeat', 'calls_to_reservation_denom_repeat'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1132, 'Среднее кол-во completed-звонков от создания сделки до брони (только сделки с бронью, созданные в периоде), (повт.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_to_reservation_avg_all', 'Звонков до брони, среднее (все)', 'Зв.до брони (вс)', 'calculated', 'decimal', '([calls_to_reservation_num] + [calls_to_reservation_num_repeat]) / ([calls_to_reservation_denom] + [calls_to_reservation_denom_repeat])', ARRAY['calls_to_reservation_num', 'calls_to_reservation_num_repeat', 'calls_to_reservation_denom', 'calls_to_reservation_denom_repeat'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1133, 'Среднее кол-во completed-звонков от создания сделки до брони (только сделки с бронью, созданные в периоде), (все). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_outbound', 'Недозвоны исходящих, сумма, перв. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1134, 'Числитель доли недозвонов (метрика 9): исходящие звонки result=''missed'', перв.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_outbound_repeat', 'Недозвоны исходящих, сумма, повт. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1135, 'Числитель доли недозвонов (метрика 9): исходящие звонки result=''missed'', повт.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_outbound_orphan', 'Недозвоны исходящих, сумма, сироты (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1136, 'Числитель доли недозвонов (метрика 9): исходящие звонки result=''missed'', сироты. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_outbound_total', 'Исходящие звонки всего, сумма, перв. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1137, 'Знаменатель доли недозвонов (метрика 9): все исходящие звонки (любой результат), перв.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_outbound_total_repeat', 'Исходящие звонки всего, сумма, повт. (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1138, 'Знаменатель доли недозвонов (метрика 9): все исходящие звонки (любой результат), повт.. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_outbound_total_orphan', 'Исходящие звонки всего, сумма, сироты (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, false, false, 'Звонки', 1139, 'Знаменатель доли недозвонов (метрика 9): все исходящие звонки (любой результат), сироты. Служебная. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_rate', 'Доля недозвонов, % (перв.)', 'Недозвон (п)', 'calculated', 'percent', '[calls_missed_outbound] / [calls_outbound_total] * 100', ARRAY['calls_missed_outbound', 'calls_outbound_total'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1140, '% missed от всех исходящих звонков (called_at в периоде), (перв.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_rate_repeat', 'Доля недозвонов, % (повт.)', 'Недозвон (пв)', 'calculated', 'percent', '[calls_missed_outbound_repeat] / [calls_outbound_total_repeat] * 100', ARRAY['calls_missed_outbound_repeat', 'calls_outbound_total_repeat'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1141, '% missed от всех исходящих звонков (called_at в периоде), (повт.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_missed_rate_all', 'Доля недозвонов, % (все)', 'Недозвон (вс)', 'calculated', 'percent', '([calls_missed_outbound] + [calls_missed_outbound_repeat] + [calls_missed_outbound_orphan]) / ([calls_outbound_total] + [calls_outbound_total_repeat] + [calls_outbound_total_orphan]) * 100', ARRAY['calls_missed_outbound', 'calls_missed_outbound_repeat', 'calls_missed_outbound_orphan', 'calls_outbound_total', 'calls_outbound_total_repeat', 'calls_outbound_total_orphan'], '{}', false, true, false, false, 1, 'avg', false, true, false, true, 'Звонки', 1142, '% missed от всех исходящих звонков (called_at в периоде), (все). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_deals_no_call', 'Сделки без единого звонка (перв.)', 'Без звонка (п)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1143, 'Кол-во сделок менеджера, созданных в периоде (created_at), у которых НЕТ ни одного звонка (любой результат) с этим deal_id, (перв.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_deals_no_call_repeat', 'Сделки без единого звонка (повт.)', 'Без звонка (пв)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1144, 'Кол-во сделок менеджера, созданных в периоде (created_at), у которых НЕТ ни одного звонка (любой результат) с этим deal_id, (повт.). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_deals_no_call_all', 'Сделки без единого звонка (все)', 'Без звонка (вс)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1145, 'Кол-во сделок менеджера, созданных в периоде (created_at), у которых НЕТ ни одного звонка (любой результат) с этим deal_id, (все). Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_silence_deals', '«Тишина» — сделки без звонков 7+ дней (перв.)', 'Тишина (п)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1146, 'Кол-во сделок менеджера «в работе» (не проданы/не отгружены/не отказ) БЕЗ единого звонка за последние 7 дней (окно — SILENCE_WINDOW_DAYS в callsMetrics.ts, дефолт 7), снимок на конец периода отчёта, (перв.). НЕ привязана к сделкам, созданным в периоде — срез по ВСЕМ открытым сделкам. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_silence_deals_repeat', '«Тишина» — сделки без звонков 7+ дней (повт.)', 'Тишина (пв)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1147, 'Кол-во сделок менеджера «в работе» (не проданы/не отгружены/не отказ) БЕЗ единого звонка за последние 7 дней (окно — SILENCE_WINDOW_DAYS в callsMetrics.ts, дефолт 7), снимок на конец периода отчёта, (повт.). НЕ привязана к сделкам, созданным в периоде — срез по ВСЕМ открытым сделкам. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES ('calls_silence_deals_all', '«Тишина» — сделки без звонков 7+ дней (все)', 'Тишина (вс)', 'external', 'int', NULL, '{}', '{}', false, true, false, false, 0, 'sum', false, false, true, false, 'Звонки', 1148, 'Кол-во сделок менеджера «в работе» (не проданы/не отгружены/не отказ) БЕЗ единого звонка за последние 7 дней (окно — SILENCE_WINDOW_DAYS в callsMetrics.ts, дефолт 7), снимок на конец периода отчёта, (все). НЕ привязана к сделкам, созданным в периоде — срез по ВСЕМ открытым сделкам. Задача КОЛСТАТ 10.07.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, is_hidden_in_ui = EXCLUDED.is_hidden_in_ui, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, calc_ok = EXCLUDED.calc_ok, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;
