-- Миграция 107: «Кол-во сделок в стадии X» за период (42 шт) + «CR Созвонился →
-- Продажа» (4 служебные + 3 CR). Задача владельца 28.07. БД: YC analytics
-- (node migrations/run_analytics.mjs migrations/107_stage_period_metrics.sql).
--
-- Семейство 1 — «Вошло в стадию: …» (перв./повт./все): потоковая пара к снимкам
-- «Стадии (сейчас)» (#2063). Семантика: сделки, ВПЕРВЫЕ (MIN(event_at) по
-- sa.deal_events) вошедшие в стадию в периоде — та же, что у знаменателей
-- «Конверсий стадий» (migrations/064). Реестр стадий — STAGE_SNAPSHOT_GROUPS
-- (stageSnapshot.ts), движок features/reports/engine/stageEntered.ts,
-- инжект только by-managers. Тройки перв./повт./все — JOIN funnels.is_repeat.
--
-- Семейство 2 — «CR Созвонился → Продажа» (перв./повт./все): движок
-- features/reports/engine/calledConversion.ts; «созвонился» = стадии с
-- ILIKE '%созвонился%' (7 стадий воронок 0/1/2/3, «Не дозвонился» не подпадает).
-- Числитель: из знаменателя те, что когда-либо ПОСЛЕ входа получили sold_at.
--
-- Данные deal_events с 03.04.2026 — раньше метрики честно null.
--
-- РЕГЛАМЕНТ КОМАНДЫ (WORKLOG #2059): пользовательские метрики скрыты в общем
-- каталоге (is_test=true + is_hidden_in_ui=true) до прод-деплоя кода-инжекта.
-- ШАГ РАЗВОРОТА при прод-релизе — UPDATE в конце файла (закомментирован).
-- Идемпотентна; is_hidden_in_ui/is_test вне ON CONFLICT SET — переезд не прячет
-- уже развёрнутые метрики.

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES
  ('stage_entered_unprocessed_count', 'Вошло в стадию: Необработанные (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1330, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Необработанные» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_unprocessed_count_repeat', 'Вошло в стадию: Необработанные (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1331, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Необработанные» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_unprocessed_count_all', 'Вошло в стадию: Необработанные (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1332, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Необработанные» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_no_answer_count', 'Вошло в стадию: Не дозвонился (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1333, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Не дозвонился» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_no_answer_count_repeat', 'Вошло в стадию: Не дозвонился (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1334, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Не дозвонился» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_no_answer_count_all', 'Вошло в стадию: Не дозвонился (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1335, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Не дозвонился» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_taken_count', 'Вошло в стадию: Взял в работу (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1336, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Взял в работу» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_taken_count_repeat', 'Вошло в стадию: Взял в работу (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1337, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Взял в работу» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_taken_count_all', 'Вошло в стадию: Взял в работу (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1338, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Взял в работу» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_contacted_count', 'Вошло в стадию: Сделал запрос снабженцу, созвонился с заказчиком (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1339, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_contacted_count_repeat', 'Вошло в стадию: Сделал запрос снабженцу, созвонился с заказчиком (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1340, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_contacted_count_all', 'Вошло в стадию: Сделал запрос снабженцу, созвонился с заказчиком (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1341, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_priced_count', 'Вошло в стадию: Созвонился и озвучил цены (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1342, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и озвучил цены» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_priced_count_repeat', 'Вошло в стадию: Созвонился и озвучил цены (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1343, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и озвучил цены» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_priced_count_all', 'Вошло в стадию: Созвонился и озвучил цены (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1344, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и озвучил цены» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_kp_sent_count', 'Вошло в стадию: Отправил КП и позвонил (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1345, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил КП и позвонил» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_kp_sent_count_repeat', 'Вошло в стадию: Отправил КП и позвонил (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1346, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил КП и позвонил» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_kp_sent_count_all', 'Вошло в стадию: Отправил КП и позвонил (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1347, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил КП и позвонил» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_next_materials_count', 'Вошло в стадию: Созвонился и уточнил следующие материалы (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1348, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и уточнил следующие материалы» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_next_materials_count_repeat', 'Вошло в стадию: Созвонился и уточнил следующие материалы (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1349, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и уточнил следующие материалы» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_next_materials_count_all', 'Вошло в стадию: Созвонился и уточнил следующие материалы (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1350, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Созвонился и уточнил следующие материалы» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_filled_planned_count', 'Вошло в стадию: Заполнил все материалы и запланировал звонок (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1351, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Заполнил все материалы и запланировал звонок» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_filled_planned_count_repeat', 'Вошло в стадию: Заполнил все материалы и запланировал звонок (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1352, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Заполнил все материалы и запланировал звонок» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_filled_planned_count_all', 'Вошло в стадию: Заполнил все материалы и запланировал звонок (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1353, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Заполнил все материалы и запланировал звонок» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_price_objection_count', 'Вошло в стадию: Есть цена дешевле, запросил предложение лучше (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1354, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Есть цена дешевле, запросил предложение лучше» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_price_objection_count_repeat', 'Вошло в стадию: Есть цена дешевле, запросил предложение лучше (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1355, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Есть цена дешевле, запросил предложение лучше» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_price_objection_count_all', 'Вошло в стадию: Есть цена дешевле, запросил предложение лучше (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1356, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Есть цена дешевле, запросил предложение лучше» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_reservation_count', 'Вошло в стадию: Забронировано (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1357, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Забронировано» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_reservation_count_repeat', 'Вошло в стадию: Забронировано (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1358, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Забронировано» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_reservation_count_all', 'Вошло в стадию: Забронировано (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1359, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Забронировано» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_contract_count', 'Вошло в стадию: Отправил счет и договор (Бронь) (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1360, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет и договор (Бронь)» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_contract_count_repeat', 'Вошло в стадию: Отправил счет и договор (Бронь) (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1361, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет и договор (Бронь)» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_contract_count_all', 'Вошло в стадию: Отправил счет и договор (Бронь) (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1362, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет и договор (Бронь)» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_confirmed_count', 'Вошло в стадию: Подтвержденная бронь (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1363, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Подтвержденная бронь» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_confirmed_count_repeat', 'Вошло в стадию: Подтвержденная бронь (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1364, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Подтвержденная бронь» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_confirmed_count_all', 'Вошло в стадию: Подтвержденная бронь (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1365, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Подтвержденная бронь» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_best_price_wait_count', 'Вошло в стадию: Наша цена лучшая, ждем оплату (Подтв.бронь) (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1366, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_best_price_wait_count_repeat', 'Вошло в стадию: Наша цена лучшая, ждем оплату (Подтв.бронь) (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1367, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_best_price_wait_count_all', 'Вошло в стадию: Наша цена лучшая, ждем оплату (Подтв.бронь) (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1368, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_sent_count', 'Вошло в стадию: Отправил счет (перв.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1369, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет» в периоде отчёта. Первичные воронки (funnels.is_repeat=false). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_sent_count_repeat', 'Вошло в стадию: Отправил счет (повт.)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1370, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет» в периоде отчёта. Повторные воронки (funnels.is_repeat=true); если одноимённой стадии в повторных воронках нет — всегда 0. Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.'),
  ('stage_entered_invoice_sent_count_all', 'Вошло в стадию: Отправил счет (все)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, true, 0, 'sum', false, false, true, false, 'Стадии (за период)', 1371, 'Сделки, ВПЕРВЫЕ (MIN(event_at) по sa.deal_events) вошедшие в стадию «Отправил счет» в периоде отчёта. Все воронки (первичные + повторные). Одноимённые стадии воронок склеены (правило #2063), охват stage_id — в коде (stageEntered.ts → STAGE_SNAPSHOT_GROUPS). Не путать со снимком «Стадии (сейчас)»: тут поток за период, там остаток на текущий момент. Данные с 03.04.2026, раньше — null. Инжектится сервером, только отчёт по менеджерам.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES
  ('stage_called_denom_primary', 'Впервые созвонился за период, первичные (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, true, false, 'Конверсии стадий', 1090, 'Знаменатель «CR Созвонился → Продажа (перв.)»: сделки первичных воронок, ВПЕРВЫЕ вошедшие в любую «созвонился»-стадию в периоде. Стадии «созвонился» резолвятся динамически (stages.name ILIKE ''%созвонился%''). Данные с 03.04.2026. Инжектится сервером (calledConversion.ts), только отчёт по менеджерам.'),
  ('stage_called_denom_repeat', 'Впервые созвонился за период, повторные (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, true, false, 'Конверсии стадий', 1091, 'Знаменатель «CR Созвонился → Продажа (повт.)»: сделки повторных воронок, ВПЕРВЫЕ вошедшие в любую «созвонился»-стадию в периоде. Стадии «созвонился» резолвятся динамически (stages.name ILIKE ''%созвонился%''). Данные с 03.04.2026. Инжектится сервером (calledConversion.ts), только отчёт по менеджерам.'),
  ('stage_called_to_sale_num_primary', 'Созвонился → продано, первичные (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, true, false, 'Конверсии стадий', 1092, 'Числитель: из знаменателя (перв.) те, что когда-либо ПОСЛЕ входа получили sold_at. Стадии «созвонился» резолвятся динамически (stages.name ILIKE ''%созвонился%''). Данные с 03.04.2026. Инжектится сервером (calledConversion.ts), только отчёт по менеджерам.'),
  ('stage_called_to_sale_num_repeat', 'Созвонился → продано, повторные (служебная)', NULL, 'external', 'int', NULL, '{}', '{}', false, true, true, false, 0, 'sum', false, false, true, false, 'Конверсии стадий', 1093, 'Числитель: из знаменателя (повт.) те, что когда-либо ПОСЛЕ входа получили sold_at. Стадии «созвонился» резолвятся динамически (stages.name ILIKE ''%созвонился%''). Данные с 03.04.2026. Инжектится сервером (calledConversion.ts), только отчёт по менеджерам.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

INSERT INTO metrics (id, name_ru, name_short_ru, metric_type, data_type, formula, dependencies, tags, is_core, is_active, is_hidden_in_ui, is_test, decimal_places, aggregation_fn, fill_ok, calc_ok, is_collect_ok, is_calc_ok, category, sort_order, description)
VALUES
  ('cr_called_to_sale', 'CR Созвонился → Продажа (перв.)', 'CR Зв→Прод (п)', 'calculated', 'percent', '[stage_called_to_sale_num_primary] / [stage_called_denom_primary] * 100', ARRAY['stage_called_to_sale_num_primary','stage_called_denom_primary'], '{}', false, true, true, true, 1, 'avg', false, true, false, true, 'Конверсии стадий', 1094, 'Конверсия «созвонился → продажа»: знаменатель — сделки, ВПЕРВЫЕ вошедшие в любую «созвонился»-стадию в периоде (stages.name ILIKE ''%созвонился%''); числитель — те из них, что когда-либо ПОСЛЕ этого получили sold_at (не только в периоде). Первичные воронки. Данные с 03.04.2026. Только отчёт по менеджерам.'),
  ('cr_called_to_sale_repeat', 'CR Созвонился → Продажа (повт.)', 'CR Зв→Прод (пв)', 'calculated', 'percent', '[stage_called_to_sale_num_repeat] / [stage_called_denom_repeat] * 100', ARRAY['stage_called_to_sale_num_repeat','stage_called_denom_repeat'], '{}', false, true, true, true, 1, 'avg', false, true, false, true, 'Конверсии стадий', 1095, 'Конверсия «созвонился → продажа»: знаменатель — сделки, ВПЕРВЫЕ вошедшие в любую «созвонился»-стадию в периоде (stages.name ILIKE ''%созвонился%''); числитель — те из них, что когда-либо ПОСЛЕ этого получили sold_at (не только в периоде). Повторные воронки. Данные с 03.04.2026. Только отчёт по менеджерам.'),
  ('cr_called_to_sale_all', 'CR Созвонился → Продажа (все)', 'CR Зв→Прод (вс)', 'calculated', 'percent', '([stage_called_to_sale_num_primary] + [stage_called_to_sale_num_repeat]) / ([stage_called_denom_primary] + [stage_called_denom_repeat]) * 100', ARRAY['stage_called_to_sale_num_primary','stage_called_to_sale_num_repeat','stage_called_denom_primary','stage_called_denom_repeat'], '{}', false, true, true, true, 1, 'avg', false, true, false, true, 'Конверсии стадий', 1096, 'Конверсия «созвонился → продажа»: знаменатель — сделки, ВПЕРВЫЕ вошедшие в любую «созвонился»-стадию в периоде (stages.name ILIKE ''%созвонился%''); числитель — те из них, что когда-либо ПОСЛЕ этого получили sold_at (не только в периоде). Первичные + повторные вместе (суммы числителей / суммы знаменателей, не среднее процентов). Данные с 03.04.2026. Только отчёт по менеджерам.')
ON CONFLICT (id) DO UPDATE SET name_ru = EXCLUDED.name_ru, name_short_ru = EXCLUDED.name_short_ru, metric_type = EXCLUDED.metric_type, data_type = EXCLUDED.data_type, formula = EXCLUDED.formula, dependencies = EXCLUDED.dependencies, aggregation_fn = EXCLUDED.aggregation_fn, category = EXCLUDED.category, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active, is_collect_ok = EXCLUDED.is_collect_ok, is_calc_ok = EXCLUDED.is_calc_ok, description = EXCLUDED.description;

-- ШАГ РАЗВОРОТА (выполнить ПОСЛЕ прод-деплоя кода-инжекта, регламент #2059):
-- UPDATE metrics SET is_test = false, is_hidden_in_ui = false WHERE id IN (
--   'stage_entered_unprocessed_count', 'stage_entered_unprocessed_count_repeat', 'stage_entered_unprocessed_count_all', 'stage_entered_no_answer_count', 'stage_entered_no_answer_count_repeat', 'stage_entered_no_answer_count_all', 'stage_entered_taken_count', 'stage_entered_taken_count_repeat', 'stage_entered_taken_count_all', 'stage_entered_contacted_count', 'stage_entered_contacted_count_repeat', 'stage_entered_contacted_count_all', 'stage_entered_priced_count', 'stage_entered_priced_count_repeat', 'stage_entered_priced_count_all', 'stage_entered_kp_sent_count', 'stage_entered_kp_sent_count_repeat', 'stage_entered_kp_sent_count_all', 'stage_entered_next_materials_count', 'stage_entered_next_materials_count_repeat', 'stage_entered_next_materials_count_all', 'stage_entered_filled_planned_count', 'stage_entered_filled_planned_count_repeat', 'stage_entered_filled_planned_count_all', 'stage_entered_price_objection_count', 'stage_entered_price_objection_count_repeat', 'stage_entered_price_objection_count_all', 'stage_entered_reservation_count', 'stage_entered_reservation_count_repeat', 'stage_entered_reservation_count_all', 'stage_entered_invoice_contract_count', 'stage_entered_invoice_contract_count_repeat', 'stage_entered_invoice_contract_count_all', 'stage_entered_confirmed_count', 'stage_entered_confirmed_count_repeat', 'stage_entered_confirmed_count_all', 'stage_entered_best_price_wait_count', 'stage_entered_best_price_wait_count_repeat', 'stage_entered_best_price_wait_count_all', 'stage_entered_invoice_sent_count', 'stage_entered_invoice_sent_count_repeat', 'stage_entered_invoice_sent_count_all', 'cr_called_to_sale', 'cr_called_to_sale_repeat', 'cr_called_to_sale_all'
-- );
