-- Migration 187: формула словами для ВСЕХ external-метрик каталога
-- БД: YC analytics (таблица metrics). Накат с ноутбука:
--   node migrations/run_local.mjs migrations/187_formula_human_all_external.sql --db=analytics
--
-- Задача владельца 24.08 (продолжение 185/186): «убедись, что АБСОЛЮТНО все
-- метрики имеют и описания, и формулы, и ссылки». Аудит показал: описания есть
-- у всех 464 активных (генератор 179), формулы — у calculated (автогенерация из
-- имён), collected (человеческий фолбэк из словарей formulaText.ts) и «Клиентов»
-- (185). Дыра — 192 external-метрики вне «Клиентов»: Звонки, Стадии за период,
-- Стадии сейчас, Конверсии стадий (служебные числители/знаменатели), Планы,
-- остатки «Повторных», Активность, мороженые, Рейтинг.
--
-- Семантика каждой семьи сверена с движками и description'ами (callsMetrics,
-- stageEntered/stageSnapshot/stageConversions, план-блок run/route.ts,
-- managerActivity, ratings) — формулы честные, не пересказ имени. Имена метрик
-- в «ёлочках» кликабельны (MetricInfoBody): «План продаж (дневной)» из формулы
-- «на текущий день» ведёт в дневной план, оттуда в месячный — до базовых.
--
-- Генерация — скриптом по шаблонам семей (192 строки руками = опечатки).
-- Тексты НЕ трогают human_description — там генератор 179 уже отработал.

BEGIN;

CREATE TABLE IF NOT EXISTS metrics_backup_187 AS SELECT * FROM metrics WHERE false;
INSERT INTO metrics_backup_187
  SELECT * FROM metrics WHERE metric_type = 'external' AND category <> 'Клиенты'
    AND NOT EXISTS (SELECT 1 FROM metrics_backup_187);

UPDATE metrics SET formula_human = $mtxt$= число подтверждённых броней периода — знаменатель «Прозвона подтв. броней»$mtxt$ WHERE id = 'booking_call_confirmed_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= подтверждённые брони, по которым позвонили не позднее следующего рабочего дня — числитель «Прозвона подтв. броней»$mtxt$ WHERE id = 'booking_call_confirmed_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число броней периода — знаменатель «Прозвона броней». Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'booking_call_reserved_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= брони, по которым позвонили не позднее СЛЕДУЮЩЕГО рабочего дня после брони — числитель «Прозвона броней»$mtxt$ WHERE id = 'booking_call_reserved_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число состоявшихся разговоров — знаменатель «Средней длительности разговора»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число состоявшихся разговоров — знаменатель «Средней длительности разговора»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число состоявшихся разговоров — знаменатель «Средней длительности разговора»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_count_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число состоявшихся разговоров — знаменатель «Средней длительности разговора»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут всех состоявшихся разговоров — числитель «Средней длительности разговора»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_duration_sum' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут всех состоявшихся разговоров — числитель «Средней длительности разговора»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_duration_sum_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут всех состоявшихся разговоров — числитель «Средней длительности разговора»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_duration_sum_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут всех состоявшихся разговоров — числитель «Средней длительности разговора»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_completed_duration_sum_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число звонков за период по дате звонка — входящие и исходящие, включая недозвоны; менеджер — кто звонил/принял; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число звонков за период по дате звонка — входящие и исходящие, включая недозвоны; менеджер — кто звонил/принял; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число звонков за период по дате звонка — входящие и исходящие, включая недозвоны; менеджер — кто звонил/принял; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_count_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число звонков за период по дате звонка — входящие и исходящие, включая недозвоны; менеджер — кто звонил/принял; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок периода, по которым не было ни одного звонка; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_deals_no_call' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок периода, по которым не было ни одного звонка; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_deals_no_call_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок периода, по которым не было ни одного звонка; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_deals_no_call_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок периода, по которым не было ни одного звонка; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_deals_no_call_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут состоявшихся входящих разговоров периода; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_in' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут состоявшихся входящих разговоров периода; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_in_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут состоявшихся входящих разговоров периода; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_in_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут состоявшихся входящих разговоров периода; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_in_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут СОСТОЯВШИХСЯ исходящих разговоров периода; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_out' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут СОСТОЯВШИХСЯ исходящих разговоров периода; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_out_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут СОСТОЯВШИХСЯ исходящих разговоров периода; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_out_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма минут СОСТОЯВШИХСЯ исходящих разговоров периода; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_duration_out_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности ПЕРВОГО разговора по каждой сделке, мин; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_first_call_duration_median' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности ПЕРВОГО разговора по каждой сделке, мин; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_first_call_duration_median_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности ПЕРВОГО разговора по каждой сделке, мин; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_first_call_duration_median_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности ПЕРВОГО разговора по каждой сделке, мин; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_first_call_duration_median_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число входящих звонков периода, привязанных к сделкам; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_incoming_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число входящих звонков периода, привязанных к сделкам; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_incoming_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число входящих звонков периода, привязанных к сделкам; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_incoming_count_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число входящих звонков периода, привязанных к сделкам; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_incoming_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности состоявшихся разговоров периода, мин. В «Итого» — настоящая медиана по всей совокупности, не среднее строк; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_median_duration' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности состоявшихся разговоров периода, мин. В «Итого» — настоящая медиана по всей совокупности, не среднее строк; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_median_duration_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности состоявшихся разговоров периода, мин. В «Итого» — настоящая медиана по всей совокупности, не среднее строк; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_median_duration_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана длительности состоявшихся разговоров периода, мин. В «Итого» — настоящая медиана по всей совокупности, не среднее строк; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_median_duration_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих недозвонов — числитель «Доли недозвонов»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_missed_outbound' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих недозвонов — числитель «Доли недозвонов»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_missed_outbound_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих недозвонов — числитель «Доли недозвонов»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_missed_outbound_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих недозвонов — числитель «Доли недозвонов»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_missed_outbound_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков всего — знаменатель «Доли недозвонов»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outbound_total' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков всего — знаменатель «Доли недозвонов»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outbound_total_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков всего — знаменатель «Доли недозвонов»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outbound_total_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков всего — знаменатель «Доли недозвонов»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outbound_total_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков периода, привязанных к сделкам; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outgoing_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков периода, привязанных к сделкам; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outgoing_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков периода, привязанных к сделкам; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outgoing_count_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число исходящих звонков периода, привязанных к сделкам; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_outgoing_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок на конец периода: сделки в работе, по которым 7 и более дней нет звонков; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_silence_deals' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок на конец периода: сделки в работе, по которым 7 и более дней нет звонков; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_silence_deals_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок на конец периода: сделки в работе, по которым 7 и более дней нет звонков; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_silence_deals_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок на конец периода: сделки в работе, по которым 7 и более дней нет звонков; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_silence_deals_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок с бронью в периоде — знаменатель «Звонков до брони»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок с бронью в периоде — знаменатель «Звонков до брони»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_denom_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок с бронью в периоде — знаменатель «Звонков до брони»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_denom_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок с бронью в периоде — знаменатель «Звонков до брони»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_denom_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= суммарное число звонков по сделкам от создания до брони — числитель «Звонков до брони»; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= суммарное число звонков по сделкам от создания до брони — числитель «Звонков до брони»; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_num_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= суммарное число звонков по сделкам от создания до брони — числитель «Звонков до брони»; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_num_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= суммарное число звонков по сделкам от создания до брони — числитель «Звонков до брони»; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_to_reservation_num_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана( время первого звонка по сделке − время создания сделки ), мин; сделки первичных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_touch_speed_median' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана( время первого звонка по сделке − время создания сделки ), мин; первичные + повторные вместе. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_touch_speed_median_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана( время первого звонка по сделке − время создания сделки ), мин; звонки без привязки к сделке. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_touch_speed_median_orphan' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана( время первого звонка по сделке − время создания сделки ), мин; сделки повторных воронок. Данные звонков — с 30.03.2026$mtxt$ WHERE id = 'calls_touch_speed_median_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= активные компании (отгрузка за 90 дней) ÷ все компании периода × 100$mtxt$ WHERE id = 'company_active_rate' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число разных товарных групп компании за всю историю$mtxt$ WHERE id = 'company_categories_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число компаний (юрлиц), чья ПЕРВАЯ отгрузка попала в период. В строке компании — 1, в «Итого» — размер когорты компаний$mtxt$ WHERE id = 'company_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= 1, если у компании была отгрузка за последние 90 дней. «Итого» — число активных компаний$mtxt$ WHERE id = 'company_is_active' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= 1, если у компании 2+ отгрузки за историю, иначе 0. «Итого» — число повторных компаний$mtxt$ WHERE id = 'company_is_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма (₽) всех отгрузок компании за всю историю$mtxt$ WHERE id = 'company_ltv' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число отгрузок компании за всю историю$mtxt$ WHERE id = 'company_orders_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= повторные компании (2+ отгрузки) ÷ все компании периода × 100. В строке — 100 или 0, честная доля — в «Итого»$mtxt$ WHERE id = 'company_repeat_rate' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: открытые сделки в стадиях типа «в работе» (первичные воронки, включая холодные звонки и тендеры). Не равен сумме стадий выше и не зависит от периода$mtxt$ WHERE id = 'deals_in_work_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: открытые сделки в стадиях типа «в работе» (все воронки). Не равен сумме стадий выше и не зависит от периода$mtxt$ WHERE id = 'deals_in_work_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: открытые сделки в стадиях типа «в работе» (повторные воронки). Не равен сумме стадий выше и не зависит от периода$mtxt$ WHERE id = 'deals_in_work_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число рабочих дней периода по производственному календарю (у всех строк отчёта одинаково)$mtxt$ WHERE id = 'manager_period_calendar_days' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число первичных сделок менеджера за период — числитель «Сделок/день»; пилюли Перв./Повт. на него не влияют$mtxt$ WHERE id = 'manager_primary_deals_activity' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= средневзвешенный балл 0–10 по осям шаблона карточки менеджера: каждая ось — перцентиль относительно менеджеров с продажами за период, веса — «Настройки → Шаблоны карточек»$mtxt$ WHERE id = 'manager_rating' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число будних дней периода, когда менеджер И получил первичную сделку, И двигал стадии сделок. Данные событий — с 03.04.2026, раньше — пусто$mtxt$ WHERE id = 'manager_worked_days_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число клиентов, купивших категорию X за всю историю (знаменатель вероятности перехода)$mtxt$ WHERE id = 'next_product_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из купивших X: у скольких есть отгрузка категории Y позже первой покупки X$mtxt$ WHERE id = 'next_product_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= клиенты, купившие Y после X ÷ клиенты, купившие X × 100. Пара показывается при поддержке от 30 клиентов$mtxt$ WHERE id = 'next_product_probability' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План продаж (дневной)» × номер текущего рабочего дня месяца (по производственному календарю)$mtxt$ WHERE id = 'plan_sales_current_day' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План продаж (дневной)» × номер текущего рабочего дня недели$mtxt$ WHERE id = 'plan_sales_current_week_day' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= месячный план продаж менеджера из «Планов»; если период задевает несколько месяцев — сумма их планов$mtxt$ WHERE id = 'plan_sales_month' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План продаж (дневной)» своего месяца × число будних дней выбранного периода (не дальше сегодня)$mtxt$ WHERE id = 'plan_sales_target_mtd' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План продаж (месяц)» ÷ 20$mtxt$ WHERE id = 'plan_sales_today' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План отгрузок (дневной)» × номер текущего рабочего дня месяца (по производственному календарю)$mtxt$ WHERE id = 'plan_shipments_current_day' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План отгрузок (дневной)» × номер текущего рабочего дня недели$mtxt$ WHERE id = 'plan_shipments_current_week_day' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= месячный план отгрузок менеджера из «Планов»; если период задевает несколько месяцев — сумма их планов$mtxt$ WHERE id = 'plan_shipments_month' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План отгрузок (дневной)» своего месяца × число будних дней выбранного периода (не дальше сегодня)$mtxt$ WHERE id = 'plan_shipments_target_mtd' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= «План отгрузок (месяц)» ÷ 20$mtxt$ WHERE id = 'plan_shipments_today' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана минут до первого касания по сделкам, созданным в периоде (первичные воронки). Замороженный исторический снапшот — новыми данными не пополняется$mtxt$ WHERE id = 'rop_first_touch_median' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана минут до первого касания по сделкам, созданным в периоде (все воронки). Замороженный исторический снапшот — новыми данными не пополняется$mtxt$ WHERE id = 'rop_first_touch_median_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= медиана минут до первого касания по сделкам, созданным в периоде (повторные воронки). Замороженный исторический снапшот — новыми данными не пополняется$mtxt$ WHERE id = 'rop_first_touch_median_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма продаж с 1-го числа текущего месяца по сегодня$mtxt$ WHERE id = 'sales_fact_month' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма продаж за выбранный период (первичные + повторные) — факт для «Выполнение плана, % (день)»$mtxt$ WHERE id = 'sales_fact_mtd' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма продаж за сегодня (МСК)$mtxt$ WHERE id = 'sales_fact_today' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма продаж с понедельника текущей недели по сегодня$mtxt$ WHERE id = 'sales_fact_week' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма отгрузок с 1-го числа текущего месяца по сегодня$mtxt$ WHERE id = 'shipments_fact_month' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма отгрузок за выбранный период (первичные + повторные) — факт для «Выполнение плана, % (день)»$mtxt$ WHERE id = 'shipments_fact_mtd' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма отгрузок за сегодня (МСК)$mtxt$ WHERE id = 'shipments_fact_today' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= сумма отгрузок с понедельника текущей недели по сегодня$mtxt$ WHERE id = 'shipments_fact_week' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, впервые вошедших в любую «созвонился»-стадию в периоде (первичные воронки). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_called_denom_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, впервые вошедших в любую «созвонился»-стадию в периоде (повторные воронки). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_called_denom_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые созвонившихся за период (первичные воронки): сколько сделок затем продано (когда угодно позже)$mtxt$ WHERE id = 'stage_called_to_sale_num_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые созвонившихся за период (повторные воронки): сколько сделок затем продано (когда угодно позже)$mtxt$ WHERE id = 'stage_called_to_sale_num_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Подтв. бронь» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_confirmed_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Подтв. бронь“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Подтв. бронь → Отказ»$mtxt$ WHERE id = 'stage_confirmed_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Подтв. бронь“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Продажа». Числитель CR «Подтв. бронь → Продажа»$mtxt$ WHERE id = 'stage_confirmed_to_sale_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Связался со снабженцем» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_contacted_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Связался со снабженцем“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Связался со снабженцем → Отказ»$mtxt$ WHERE id = 'stage_contacted_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Связался со снабженцем“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Озвучил цену/КП». Числитель CR «Связался со снабженцем → Озвучил цену/КП»$mtxt$ WHERE id = 'stage_contacted_to_priced_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_best_price_wait_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_best_price_wait_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Наша цена лучшая, ждем оплату (Подтв.бронь)» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_best_price_wait_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Подтвержденная бронь» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_confirmed_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Подтвержденная бронь» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_confirmed_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Подтвержденная бронь» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_confirmed_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_contacted_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_contacted_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Сделал запрос снабженцу, созвонился с заказчиком» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_contacted_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Заполнил все материалы и запланировал звонок» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_filled_planned_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Заполнил все материалы и запланировал звонок» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_filled_planned_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Заполнил все материалы и запланировал звонок» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_filled_planned_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет и договор (Бронь)» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_contract_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет и договор (Бронь)» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_contract_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет и договор (Бронь)» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_contract_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_sent_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_sent_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил счет» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_invoice_sent_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил КП и позвонил» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_kp_sent_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил КП и позвонил» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_kp_sent_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Отправил КП и позвонил» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_kp_sent_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и уточнил следующие материалы» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_next_materials_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и уточнил следующие материалы» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_next_materials_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и уточнил следующие материалы» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_next_materials_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Не дозвонился» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_no_answer_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Не дозвонился» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_no_answer_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Не дозвонился» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_no_answer_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Есть цена дешевле, запросил предложение лучше» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_price_objection_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Есть цена дешевле, запросил предложение лучше» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_price_objection_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Есть цена дешевле, запросил предложение лучше» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_price_objection_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и озвучил цены» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_priced_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и озвучил цены» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_priced_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Созвонился и озвучил цены» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_priced_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Забронировано» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_reservation_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Забронировано» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_reservation_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Забронировано» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_reservation_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Взял в работу» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_taken_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Взял в работу» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_taken_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Взял в работу» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_taken_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Необработанные» в периоде (первичные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_unprocessed_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Необработанные» в периоде (все воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_unprocessed_count_all' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в стадию «Необработанные» в периоде (повторные воронки; первый вход за историю сделки, одноимённые стадии физ/юр склеены). Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_entered_unprocessed_count_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Новая» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_new_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Новая“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Новая → Отказ»$mtxt$ WHERE id = 'stage_new_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Новая“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Взял в работу». Числитель CR «Новая → Взял в работу»$mtxt$ WHERE id = 'stage_new_to_taken_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Наша цена лучшая, ждем оплату (Подтв.бронь)» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_best_price_wait_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Подтвержденная бронь» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_confirmed_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Сделал запрос снабженцу, созвонился с заказчиком» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_contacted_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Заполнил все материалы и запланировал звонок» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_filled_planned_call_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Отправил счет и договор (Бронь)» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_invoice_contract_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Отправил счет» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_invoice_sent_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Отправил КП и позвонил» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_kp_sent_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Созвонился и уточнил следующие материалы» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_next_materials_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Не дозвонился» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_no_answer_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Есть цена дешевле, запросил предложение лучше» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_price_objection_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Созвонился и озвучил цены» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_priced_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Забронировано» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_reservation_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Взял в работу» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_taken_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= снимок ПРЯМО СЕЙЧАС: сколько сделок стоит в стадии «Необработанные» (физ + юр воронки вместе). Период отчёта не влияет$mtxt$ WHERE id = 'stage_now_unprocessed_count' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, впервые вошедших в стадию «Есть цена дешевле» в периоде (первичные воронки). Знаменатель CR из этой стадии$mtxt$ WHERE id = 'stage_price_lower_denom_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, впервые вошедших в стадию «Есть цена дешевле» в периоде (повторные воронки). Знаменатель CR из этой стадии$mtxt$ WHERE id = 'stage_price_lower_denom_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (первичные воронки): сколько затем достигли «Отказ»$mtxt$ WHERE id = 'stage_price_lower_to_lost_num_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (повторные воронки): сколько затем достигли «Отказ»$mtxt$ WHERE id = 'stage_price_lower_to_lost_num_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (первичные воронки): сколько затем достигли «Бронь»$mtxt$ WHERE id = 'stage_price_lower_to_reservation_num_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (повторные воронки): сколько затем достигли «Бронь»$mtxt$ WHERE id = 'stage_price_lower_to_reservation_num_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (первичные воронки): сколько затем достигли «Продажа»$mtxt$ WHERE id = 'stage_price_lower_to_sale_num_primary' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из впервые вошедших в «Есть цена дешевле» за период (повторные воронки): сколько затем достигли «Продажа»$mtxt$ WHERE id = 'stage_price_lower_to_sale_num_repeat' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Озвучил цену/КП» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_priced_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Озвучил цену/КП“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Озвучил цену/КП → Отказ»$mtxt$ WHERE id = 'stage_priced_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Озвучил цену/КП“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Бронь». Числитель CR «Озвучил цену/КП → Бронь»$mtxt$ WHERE id = 'stage_priced_to_reservation_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Бронь» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_reservation_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Бронь“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Подтв. бронь». Числитель CR «Бронь → Подтв. бронь»$mtxt$ WHERE id = 'stage_reservation_to_confirmed_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Бронь“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Бронь → Отказ»$mtxt$ WHERE id = 'stage_reservation_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Продажа» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_sale_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Продажа“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Продажа → Отказ»$mtxt$ WHERE id = 'stage_sale_to_lost_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Продажа“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отгрузка». Числитель CR «Продажа → Отгрузка»$mtxt$ WHERE id = 'stage_sale_to_shipment_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= число сделок, ВПЕРВЫЕ вошедших в группу стадий «Взял в работу» в периоде (первый вход за историю сделки, физ+юр воронки вместе). Знаменатель всех CR из этой стадии. Данные событий — с 03.04.2026$mtxt$ WHERE id = 'stage_taken_denom' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Взял в работу“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Связался со снабженцем». Числитель CR «Взял в работу → Связался со снабженцем»$mtxt$ WHERE id = 'stage_taken_to_contacted_num' AND formula_human IS NULL;
UPDATE metrics SET formula_human = $mtxt$= из когорты «впервые в „Взял в работу“ за период»: сколько сделок затем (когда угодно позже, не только в периоде) впервые дошли до «Отказ». Числитель CR «Взял в работу → Отказ»$mtxt$ WHERE id = 'stage_taken_to_lost_num' AND formula_human IS NULL;

COMMIT;
